// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Caja struct {
	Monedas50centavos *float64 `json:"monedas50centavos"`
	Monedas1Peso      *float64 `json:"monedas1Peso"`
	Monedas2Pesos     *float64 `json:"monedas2Pesos"`
	Monedas5Pesos     *float64 `json:"monedas5Pesos"`
	Monedas10Pesos    *float64 `json:"monedas10Pesos"`
	Monedas20Pesos    *float64 `json:"monedas20Pesos"`
	Billetes20        *float64 `json:"billetes20"`
	Billetes50        *float64 `json:"billetes50"`
	Billetes100       *float64 `json:"billetes100"`
	Billetes200       *float64 `json:"billetes200"`
	Billetes500       *float64 `json:"billetes500"`
	Billetes1000      *float64 `json:"billetes1000"`
}

type ModificarUsuario struct {
	ID     string  `json:"id"`
	Nombre *string `json:"nombre"`
	Mail   *string `json:"mail"`
	Nick   string  `json:"nick"`
	Pass   string  `json:"pass"`
	Admin  *bool   `json:"admin"`
	Root   *bool   `json:"root"`
}

type Observacion struct {
	Descripcion *string  `json:"descripcion"`
	Egreso      *float64 `json:"egreso"`
}

type Producto struct {
	ID          string   `json:"id"`
	Nombre      *string  `json:"nombre"`
	Descripcion *string  `json:"descripcion"`
	Precio      *float64 `json:"precio"`
}

type Responsiva struct {
	NumeroCaja        int            `json:"numeroCaja"`
	FechaEntrada      *string        `json:"fechaEntrada"`
	FechaSalida       *string        `json:"fechaSalida"`
	UsuarioEncargado  *Usuario       `json:"usuarioEncargado"`
	UsuarioReceptor   *Usuario       `json:"usuarioReceptor"`
	Productos         []*Producto    `json:"productos"`
	ProductosVendidos []*Producto    `json:"productosVendidos"`
	Observaciones     []*Observacion `json:"observaciones"`
	Caja              *Caja          `json:"caja"`
}

type Sucursal struct {
	ID          string        `json:"id"`
	Nombre      *string       `json:"nombre"`
	Direccion   *string       `json:"direccion"`
	Productos   []*Producto   `json:"productos"`
	Usuarios    []*Usuario    `json:"usuarios"`
	Responsivas []*Responsiva `json:"responsivas"`
}

type Usuario struct {
	ID     string  `json:"id"`
	Nombre *string `json:"nombre"`
	Mail   *string `json:"mail"`
	Nick   string  `json:"nick"`
	Pass   string  `json:"pass"`
	Admin  *bool   `json:"admin"`
	Root   *bool   `json:"root"`
}
